using System.Collections.Generic;
using UnityEngine;

namespace Starquill.Display
{
    /// Per-category icon crop rects for equipment sprites.
    ///
    /// Every item image is a full 200x200 character-sized canvas with the item
    /// drawn where it sits on the body, so raw sprites land at wildly different
    /// sizes and positions when shown off-character (boots: a sliver at the
    /// bottom; hats: high and wide). These rects are the project-wide default
    /// framing for item icons: a square uvRect (bottom-left origin) centered on
    /// the category's alpha-weighted mean pixel center, sized so >=95% of the
    /// category's items fit fully with 5% padding.
    ///
    /// Generated by tools/analyze_item_framing.py (2026-07-01, 2,808 sprites).
    /// Rerun the script and paste the table here when item art changes.
    public static class ItemIconFraming
    {
        private static readonly Dictionary<string, Rect> Frames = new()
        {
            { "ar", new Rect(0.2978f, 0.1777f, 0.3864f, 0.3864f) },
            { "fe", new Rect(0.3401f, 0.0167f, 0.2560f, 0.2560f) },
            { "hd", new Rect(0.1279f, 0.2827f, 0.7173f, 0.7173f) },
            { "lg", new Rect(0.2957f, 0.1069f, 0.3413f, 0.3413f) },
            { "mc", new Rect(0.1323f, 0.0943f, 0.6576f, 0.6576f) },
            { "tr", new Rect(0.1408f, 0.0991f, 0.6669f, 0.6669f) },
            { "w01", new Rect(0.0802f, 0.0000f, 0.8040f, 0.8040f) },
            { "w02", new Rect(0.2814f, 0.0000f, 0.5726f, 0.5726f) },
            { "w03", new Rect(0.2823f, 0.0492f, 0.4546f, 0.4546f) },
            { "w04", new Rect(0.0000f, 0.0000f, 1.0000f, 1.0000f) },
            { "w05", new Rect(0.0496f, 0.0000f, 0.9504f, 0.9504f) },
            { "w06", new Rect(0.2662f, 0.1206f, 0.3958f, 0.3958f) },
            { "w07", new Rect(0.1202f, 0.0156f, 0.6231f, 0.6231f) },
            { "w08", new Rect(0.2459f, 0.2087f, 0.3599f, 0.3599f) },
            { "w09", new Rect(0.2440f, 0.1955f, 0.3734f, 0.3734f) },
        };

        private static readonly Rect FullFrame = new(0f, 0f, 1f, 1f);

        /// Crop rect for an item type ("tr03", "w05", ...). Weapon types match
        /// their full "wNN" prefix; armor matches the two-letter prefix.
        public static Rect GetFrame(string itemType)
        {
            if (string.IsNullOrEmpty(itemType)) return FullFrame;

            if (itemType.Length >= 3 && itemType[0] == 'w'
                && char.IsDigit(itemType[1]) && char.IsDigit(itemType[2])
                && Frames.TryGetValue(itemType.Substring(0, 3), out var weaponFrame))
                return weaponFrame;

            if (itemType.Length >= 2
                && Frames.TryGetValue(itemType.Substring(0, 2), out var frame))
                return frame;

            return FullFrame;
        }
    }
}
